---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
      region: ap-southeast-1
      instance_type: t2.micro
      ami: ami-76144b0a  # Red Hat Enterprise Linux 7.5 (HVM), SSD Volume Type  
      security_group: SSH only
      keypair: Linux_Test_1_Key # pem file name
      count: 1

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         vpc_subnet_id: subnet-0f2572b12601ee10b
         assign_public_ip: yes
      register: ec2 #register: ec2 registers the output in ec2 variable in a playbook it may be useful to store the result of a given command in a variable and access it later.

    #- name: Add the newly created host so that we can further contact it
      #add_host:
        #hostname: "{{ item.public_ip }}"
        #groups: webservers
      #with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"

    - name: "Artifact URL of test results to Tower Workflows"
      set_stats:
        data:
          results:  "{{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"
