---
- name: Ansible Demo for Linux
  hosts: all
  tasks:
    - name: Stop httpd service
      service:
        name: httpd
        state: stopped

    - name: Stop firewalld service
      service:
        name: firewalld
        state: stopped

    - name: Shutdown machine
      command: /sbin/shutdown -h now
