---
- name: Ansible Demo for Windows
  hosts: all
  tasks:
    - name: Stop Windows Firewall
      win_service:
        name: Windows Firewall
        state: stopped

    - name: Shutdown
      win_command: shutdown /s
