---
- name: Ansible Demo for Windows
  hosts: all
  tasks:
    - name: Stop Windows Firewall
      win_firewall:
        state: disabled
        profiles:
        - Domain
        - Private
        - Public
